services:
  postgres:
    image: postgres:16
    restart: on-failure
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: secret1234
      POSTGRES_DB: attendance_db
    networks:
      - attendance_network

  pgAdmin4:
    image: dpage/pgadmin4:latest
    depends_on:
      - postgres
    ports:
      - "8083:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: dev@gmail.com
      PGADMIN_DEFAULT_PASSWORD: dev1234
    networks:
      - attendance_network

networks:
  attendance_network:
