spring:
  application:
    name: attendancemanagementapi

  datasource:
    url: jdbc:postgresql://localhost:5433/attendance_db
    username: dev
    password: secret1234
    driver-class-name: org.postgresql.Driver

  jpa:
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
