spring:
  application:
    name: attendancemanagementapi

  datasource:
    url: jdbc:postgresql://localhost:5433/attendance_db
    username: dev
    password: secret1234
    driver-class-name: org.postgresql.Driver

  jpa:
    database: POSTGRESQL
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: maxijeanrene@gmail.com
    password: wecl qnum ctxj fhnz
    properties:
      mail:
        smtp:
          auth: true
          starttls: 
            enable: true
            required: true

api:  
  base: 
   url: http://localhost:8080
  jwt-secret: mysuperlongsecuresecretkeythatshouldbeatleast64characterslong123456
  jwt-expiration: 2592000000
  jwt-issuer: ticket-api-issuer
